### PR TITLE
Illustrations computer software and hardware

### PR DESCRIPTION
**Pull request by dengyijialiu0**
- added the illustrations for the software and hardware article

### CODE REVIEW

**Review by hpyhacking — CHANGES_REQUESTED** [review]
fix typo please
`s/fiqures/figures/g`

**Comment by hpyhacking** [comment]
keep files capitalization 
etc. `s/Lisa/lisa/g`

**Comment by hpyhacking** [comment]
@andreigue could follow this PR changing image path in the article.

**Comment by andreigue** [comment]
Illustrations have been added to the markdown files. Please check

**Review by hpyhacking — APPROVED** [review]

**Pull request merged**
